version: "3.8"

services:
  mysql-primary:
    # image: mysql:latest
    image: mysql:5.7.12
    container_name: mysql-primary
    restart: unless-stopped
    tty: true

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-myrootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-mydb}
      MYSQL_USER: ${MYSQL_USER:-myuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-myuserpassword}
      # TZ: ${TZ}

    command: [
        "--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION",
        # '--innodb-dedicated-server=ON',
        "--max_allowed_packet=500M",
        "--default-authentication-plugin=mysql_native_password",
        "--server-id=1",
        "--binlog-do-db=${MYSQL_DATABASE:-mydb}",
      ]
    cap_add:
      - all
    ports:
      - ${MYSQL_PORT:-3306}:3306
    expose:
      - ${MYSQL_PORT:-3306}
    volumes:
      - ./primary/conf.d:/etc/mysql/conf.d
      - ./primary/log/mysql:/var/log/mysql
      - ./primary/data:/var/lib/mysql
    networks:
      mysql_network:
        ipv4_address: 172.26.0.254

  mysql-secondary:
    # image: mysql:latest
    image: mysql:5.7.12
    container_name: mysql-secondary
    restart: unless-stopped
    tty: true
    depends_on:
      - mysql-primary

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-myrootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-mydb}
      MYSQL_USER: ${MYSQL_USER:-myuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-myuserpassword}
      # TZ: ${TZ}

    command: [
        "--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION",
        # '--innodb-dedicated-server=ON',
        "--max_allowed_packet=500M",
        "--default-authentication-plugin=mysql_native_password",
        "--server-id=2",
        "--replicate-do-db=${MYSQL_DATABASE:-mydb}",
      ]
    cap_add:
      - all
    ports:
      - ${SECONDARY_MYSQL_PORT:-3307}:3306
    expose:
      - ${SECONDARY_MYSQL_PORT:-3307}
    volumes:
      - ./secondary/conf.d:/etc/mysql/conf.d
      - ./secondary/log/mysql:/var/log/mysql
      - ./secondary/data:/var/lib/mysql
    networks:
      mysql_network:
        ipv4_address: 172.26.0.253

  phpmyadmin:
    env_file:
      - .env
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    restart: always
    depends_on:
      - mysql-primary
      - mysql-secondary
    environment:
      PMA_HOSTS: "mysql-primary,mysql-secondary"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-myrootpassword}
      UPLOAD_LIMIT: 254M
      MAX_EXECUTION_TIME: 60000
      #VIRTUAL_HOST: ${VIRTUAL_HOST}
      #LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
      #LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    ports:
      - 8080:80
    volumes:
      - /sessions
    networks:
      mysql_network:
        ipv4_address: 172.26.0.2

networks:
  mysql_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.0.0/16
          gateway: 172.26.0.1

volumes:
  mysql_primary_data:
  mysql_secondary_data:
